baseurl = "/"
languageCode = "en-us"
title = "Kyle Boyle"
theme = "crisp_kyle"
DisqusShortname = "kyleboylecom"
googleAnalytics = "UA-74726625-1"

[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Kyle Boyle"
    defaultKeywords = "Kyle Boyle"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"
