baseURL = "https://kyleboyle.com/"
languageCode = "en-us"
title = "Kyle Boyle's Homepage"
theme = "basic"

# for github pages
publishDir = "docs"

[params]
  github = "https://github.com/kyleboyle"
  linkedin = "https://www.linkedin.com/in/kyboyle/"