baseurl = "/"
languageCode = "en-us"
title = "Kyle Boyle"
theme = "crisp_kyle"

[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Kyle Boyle"
    defaultKeywords = "Kyle Boyle"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    tagline = "Don't"

    # Metadata used to drive integrations.
    googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "Your Google Analytics tracking code"
    #gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, avoid enabling too many of these if possible.
    # These should be full URLs.
    github = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = ""